title: SPARCie's site
markdown: kramdown
url: "https://www.sparcie.tk"
baseurl: "/"

# for atom feed
author:
  name: SPARCie aka Jeroen
  email: no@spam.sus

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
